export const SAVE_PRODUCTS = 'SAVE_PRODUCTS'
export const PRODUCTS_LOADING_START = 'PRODUCTS_LOADING_START'
export const PRODUCTS_LOADING_SUCCESS = 'PRODUCTS_LOADING_SUCCESS'
export const PRODUCTS_LOADING_FAILURE = 'PRODUCTS_LOADING_FAILURE'
